version: "3"
services:
  app:
    container_name: MkRadar
    build: ./
    restart: unless-stopped
    environment:
      LOG_LEVEL: "INFO"
      MK_RADAR_BUILD_PATH: "website"
      GITHUB_TOKEN: "..."
      BITBUCKET_USERNAME: "..."
      BITBUCKET_APP_PASSWORD: "..."
      GITLAB_TOKEN: "..."
    volumes:
      - ./:/app
