version: "3"
services:
  app:
    container_name: MkRadar
    build: ./
    restart: unless-stopped
    environment:
      MK_RADAR_BUILD_PATH: "website"
      GITHUB_TOKEN: "..."
      BITBUCKET_USERNAME: "..."
      BITBUCKET_APP_PASSWORD: "..."
      GITLAB_TOKEN: "..."
      AWS_PROFILE: ""
      S3_BUCKET_NAME: ""
      S3_BUCKET_DESTINATION: ""
