wikiPages:
  -
    title: aws-nuke
    category: OPS
    type: public
    url: "https://github.com/rebuy-de/aws-nuke/blob/master/README.md"
  -
    category: OPS
    title: site24*7
    type: public
    notification: false
    tags: "terraform, go, shell"
    url: "https://github.com/Bonial-International-GmbH/terraform-provider-site24x7/blob/master/Makefile"